[deploy]
bucket = 'cfn-artifacts-eap'
region = 'us-east-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:895593147410:certificate/460d40eb-edce-4961-a59b-ba03b462c7f1'
NetworkingStack = 'CrdNet'